# -*- coding: utf-8 -*-
"""Capitulo_3_parte_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCkQztnL2kPlvKVkIa9dnRPqQWO46OKP

**Primer paso**
"""

#Variables del Sistema:
tamiz_200 = 2                     #% pasa
if tamiz_200 > 50 :               #criterio finos
  print("Mundo de los finos")
else:                             #criterio gruesos
  print("Mundo de las Gruesos")

"""**Segundo Paso**"""

#Variables del Sistema:
tamiz_200 = 2                     #% pasa
tamiz_4 = 60                      #% pasa
if tamiz_200 > 50 :               #criterio finos
  print("Mundo de los finos")
else:                             #criterio gruesos
  print("Mundo de las Gruesos")
  if tamiz_4 > 50:                #criterio Gravas
    print("Gravas")
  else:                           #criterio Arena
    print("Arenas")

"""**Tercer paso**"""

#Variables del Sistema:
tamiz_200 = 2                     #% pasa
tamiz_4 = 60                      #% pasa
if tamiz_200 > 50 :               #criterio finos
  print("Mundo de los finos")
else:                             #criterio gruesos
  print("Mundo de las Gruesos")
  if tamiz_4 > 50:                #criterio Gravas
    if 0<tamiz_200<5:             #Primer Criterio
      print("Ocurre algo A")
    elif 5<tamiz_200<12:          #Segundo Criterio
        print("Ocurre algo B")
    else:                         #Tercer Criterio
      print("Ocurre algo C")
  else:                           #criterio Arena
    print("Arenas")

"""**Cuarto Paso**"""

#Variables del Sistema:
tamiz_200 = 2                     #% pasa
tamiz_4 = 60                      #% pasa
Cu = 3                            #Coeficiente uniformidad
Cc = 2                            #Coeficiente Curvatura
if tamiz_200 > 50 :               #criterio finos
  print("Mundo de los finos")
else:                             #criterio gruesos
  if tamiz_4 > 50:                #criterio Gravas
    if 0<tamiz_200<5:             #Primer Criterio
      if Cu >= 6 and 1<=Cc<=3:    #Criterio Bien gradado
        print("SW")
      else:                       #Criterio Mal gradado
        print("SP")
    elif 5<tamiz_200<12:          #Segundo Criterio
        print("Ocurre algo B")
    else:                         #Tercer Criterio
      print("Ocurre algo C")
  else:                           #criterio Arena
    print("Arenas")

"""**Código Finalizado**"""

#Variables del código
tamiz_200 = 2                     #% pasa
tamiz_4 = 60                      #% pasa
Cu = 3                            #Coeficiente uniformidad
Cc = 2                            #Coeficiente Curvatura
#Desarrollo del código
if tamiz_200 > 50 :               #criterio finos
  print("Mundo de los finos")
else:                             #criterio gruesos
  if tamiz_4 > 50:                #criterio Gravas
    if 0<tamiz_200<5:             #Primer Criterio
      if Cu >= 6 and 1<=Cc<=3:    #Criterio Bien gradado
        print("SW")
      else:                       #Criterio Mal gradado
        print("SP")
    elif 5<tamiz_200<12:          #Segundo Criterio
      if Cu >= 6 and 1<=Cc<=3:    #Criterio Bien gradado
        print("SW")
        #cartaPlasticidad()
      else:                       #Criterio Mal gradado
        print("SP")
        #cartaPlasticidad()
    else:                         #Tercer Criterio
      print("S")
      #cartaPlasticidad()
  else:
    print("Mundo de las Gravas")  #Se invita al lector a desarrollar estas líneas de código.